# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'im_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageTheory(object):
    def setupUi(self, Form):
        Form.setObjectName("Рисунки для теории")
        Form.resize(500, 400)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.choose_im = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_im.sizePolicy().hasHeightForWidth())
        self.choose_im.setSizePolicy(sizePolicy)
        self.choose_im.setObjectName("choose_im")
        self.gridLayout.addWidget(self.choose_im, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setObjectName("btn")
        self.gridLayout.addWidget(self.btn, 1, 0, 1, 1)
        self.image = QtWidgets.QLabel(Form)
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 1, 1, 2, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Рисунки для теории"))
        self.label.setText(_translate("Form", "Выбрать рисунок:"))
        self.btn.setText(_translate("Form", "Загрузить"))
